### ISSUE TITLE
Setting bool properties

### ISSUE THREAD

**Issue by jpbrodsky** [SNiPER-Framework/sniper#25]
Bool properties of algorithms cannot be set via python.

```
template <>
inline void SniperJSON::toCppVar<bool>(bool &var) const
{
    if (m_type == 9)
    {
        if (m_jvar == "true")
        {
            var = true;
            return;
        }
        else if (m_jvar == "false")
        {
            var = false;
            return;
        }
    }

    throw Exception(std::string("cannot set <bool> with <") + m_jvar + '>');
}
```
To set a bool property, the above code is run. However, there are two issues:

1. The process of passing a string "false" from a python runscript into `MyAlg.property("BoolProperty").set('false')` causes the string to be converted into "\"false\"", presumably as part of the boost python interface. This string does not match either case in the above code.
2. When a string is provided, m_type==3, so the above code always fails immediately. m_type==9 indicates a scalar value, but the code above cannot match any scalar value.

**Comment by zoujh** [comment]
Hi @jpbrodsky , please use python `True` or `False` but not a string just the same as in SNiPER v1. You can find the [example in run-HelloWorld](https://github.com/SNiPER-Framework/sniper/blob/a95739fa9da0bd563fbdf9dfd8e8afc5f236dc4b/Examples/CoreUsages/options/run-HelloWorld.py#L17). 

In SNiPER v2, there is an conversion from python object to json and then to cpp for properties, so that the SniperKernel module is independent of boost.python any more. You can also have a look at the new executable `sniper.exe`, by which we can use [a json file](https://github.com/SNiPER-Framework/sniper/blob/master/Examples/CoreUsages/options/run-HelloWorld.json) to configure a job without python (and boost.python). The 2 configuration methods are equivalent.

**Comment by jpbrodsky** [comment]
Thank you for the clarification. This is working for me.
